version: '3'
services:
  mysql:
    container_name: mysql
    ports:
     - "192.168.122.48:8080:80"
     - "192.168.122.48:3306:3306"
    image: "theraw/rocky:mysql"
    privileged: true
    restart: unless-stopped
    networks:
      rocky_net:
        ipv4_address: 172.69.0.70

  dashboard:
    container_name: dashboard
    ports:
     - "192.168.122.48:80:80"
     - "192.168.122.48:443:443"
    image: "default"
    privileged: true
    restart: unless-stopped
    networks:
      rocky_net:
        ipv4_address: 172.69.0.72

networks:
  rocky_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.69.0.0/16
